### PR TITLE
copy connection for projection

### PR DESCRIPTION
**Pull request by DavidBadura**
During the tutorial I discovered that you can use the event store and subscription engine without Doctrine Bundle. But as soon as you want to write your projections with dbal, you have to install DoctrineBundle or set up the connection yourself.
(You cannot use the same connection as the one for event sourcing, otherwise the subscription engine will break)

So you currently have the following options:

1) You build a connection service yourself, which is cumbersome.

2) You install DoctrineBundle, but you immediately get an error message that the orm package is missing and you have to remove orm config first.

Bildschirmfoto 2024-12-05 um 11 13 59

We recommend using DoctrineBundle if you want all the Dbal features like extended configuration options, logger and profiler. But for the start and tutorial it is unfortunate.

I also didn't want to duplicate the features of DoctrineBundle here. That wouldn't make sense.

I also looked to see if our bundle should require DoctrineBundle directly, but that isn't that easy to implement either, as we would have to manipulate the config. It could also be that you don't want to use dbal then we could have saved ourselves that.

So I came up with the simple solution of offering the option to build a second connection with the same URL, which you can then use in your projection. That is the simplest solution without having to go through DoctrineBundle.

The naming of the option is not good yet. Here are a few ideas:

* use_for_projection
* publish_connection

### CODE REVIEW

**Comment by DanielBadura** [comment]
Regarding naming of the option: `copy_for_projection` could also be a good candidate.

I'll just toss the other possbility in here, where the user configures a different url and mark it as using for proejction:
```yaml
connection:
    url: ''
projectionConnection: 
    url: ''
    use_for_projection: true
```

instead of the current proposed:

```yaml
connection:
    url: ''
    use_for_projection: true
```

**Comment by DavidBadura** [comment]
I would go with `provide_dedicated_connection`. I think that describes it best. I have also expanded the documentation and tried to describe everything accordingly. Additionally I will set it default to true in our flex recipe.

**Comment by DavidBadura** [comment]
What do you think about `extra_connection` as naming?

```yaml
connection:
    url: //...
    extra_connection: true
```

**Review by DanielBadura — APPROVED** [review]
IMHO this option is still confusing from user PoV. But I could not come up with a better solution myself. So let's ship it - since user are hit by this regular. We could still update it later on, if we come up with something better.

**Pull request merged**
