### PR TITLE
Fix getting started section in the documentation

### LINKED ISSUE #158: 2.3.x getting started code example issues
Great work on this library!

There are several issues with the  code example provided in the docs.

Besides the semantic issues, the example will not work with the default installation, because the table `hotel` will conflict between the projection and the event store.
This would require either, change the projection table name, or set the project to use a single event store (I'd say easier to start with anyway, but a bit less out-of-the-box).

### PR DESCRIPTION
**Pull request by kochen**
closes #158

### CODE REVIEW

**Comment by DanielBadura** [comment]
Thanks for the fixes!

One question tho: Why the change from `toString` to `jsonSerialize` for the `Uuid`? Looking in the implementation of the `AbstractUid`  & `Uuid` classes the result should be the same.

**Comment by kochen** [comment]
@DanielBadura because `toString` doesn't exists.
it's either `__toString` or `jsonSerialize`:
```PHP
    public function __toString(): string
    {
        return $this->uid;
    }

    public function jsonSerialize(): string
    {
        return $this->uid;
    }
```

**Review by DavidBadura — APPROVED** [review]
I checked again and you're right, this method doesn't exist in symfony < 7.1. This was only added from Symfony 7.1.

`jsonSerialize` is not really the right method (from context and naming) to return the value. But it does exactly the same as `__toString`.

The other option here would be `(string)$this->id`, which also has the disadvantage that `null` results in an empty string, which then leads to strange errors.

Unfortunately, toString was only added from 7.1 and since we don't require >= 7.1, I think your solution is best.

We are about to release event sourcing version 3.0 soon. The handling of the aggregate ID has been improved there and we also provide an default ID implementation. That's why this problem will no longer exist in the future.

What do you think @DanielBadura?

**Comment by kochen** [comment]
I suggest using `(string)$this->uid` and keeping the "old version" clean and usable just in case someone still wants to try it.

**Comment by DavidBadura** [comment]
I thought about it too. Because the property does not also have type `null`, the `null` case cannot happen at all. 
I would also use `(string)$this->id` now. Can you change that?

**Review by DanielBadura — APPROVED** [review]

**Comment by DanielBadura** [comment]
Thanks @kochen!

**Comment by kochen** [comment]
@DanielBadura  could/would this be merged into `3.x` as well?
otherwise I could create a new MR...

**Comment by DanielBadura** [comment]
We will merge it up, we need to do some more syncing things there. Thanks!

**Pull request merged**
